language: smalltalk
sudo: false

notifications:
    email:
        on_success: never
        on_failure: always

os:
- osx

smalltalk:
  - Moose-7.0

matrix:
  allow_failures:
    - smalltalk: Moose-8.0
