language: smalltalk
sudo: false

notifications:
    email:
        on_success: never
        on_failure: always
        
smalltalk:
  - Moose32-7.0
  - Moose64-7.0

matrix:
  allow_failures: # Allow bleeding edge builds to fail
    - smalltalk_config: .bleedingEdge.ston
  include:
    - smalltalk: Moose64-8.0
      smalltalk_config: .bleedingEdge.ston
    - smalltalk: Moose32-8.0
      smalltalk_config: .bleedingEdge.ston
