language: smalltalk
sudo: false

notifications:
    email:
        on_success: never
        on_failure: always

os:
- osx

matrix:
  allow_failures:
    - smalltalk: Moose64-8.0
    - smalltalk: Moose32-8.0
    - smalltalk: Moose64-7.0

  include:
    smalltalk: Moose32-7.0
