# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the development branch
on:
  push:
    branches: 
      - main
      - v*
      - master
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: PharoLanguageServer
    strategy:
      matrix:
        smalltalk: [ Moose64-9.0]
    name: ${{ matrix.smalltalk }}
    steps:
      - uses: actions/checkout@v2
      
      - uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-version: ${{ matrix.smalltalk }}
      
      - run: smalltalkci -s ${{ matrix.smalltalk }}
        shell: bash
        timeout-minutes: 15

      - name: Build meta-model planuml image
        run: |
          $SMALLTALK_CI_VM  $SMALLTALK_CI_IMAGE eval "'uml.uml' asFileReference writeStreamDo: [ :stream | stream nextPutAll:  (FamixMMUMLDocumentor new model: CSNModel; beWithStub; generatePlantUMLModel)]."
    
      - name: check directory
        run: ls
      
      - name: check home directory
        run: ls ~
      
      
      - name: Generate PNG Diagrams
        uses: cloudbees/plantuml-github-action@master
        with:
            args: -v -tpng uml.uml
      
      - name: check directory
        run: ls
        
      - name: check home directory
        run: ls ~
      
      
